### ISSUE TITLE
How to make these hacks work in genesis plus gx core (retroarch)

### ISSUE THREAD

**Issue by pepodmc** [krikzz/msu-md#1]
I tried first making it work in kega fusion (it supports the rock and roll racing mode 1 hack", but with streets of rage 2 and outrun it shows distorted and missing graphics, then i find this information in a forum:

"When I created a mode 1 for Chaos Layer, I had a similar problem. Turns out, Kega doesn't perform DMA transfers from ROM correctly in this mode.

Sonic 1 remains unaffected, because all DMA transfers in that game, are always done from RAM, never from ROM (likely due to the cartridge type at the time)."

So i will try with the genesis plus GX core in retroarch, but i dont know how to make it work, i put the cue with the same name as the rom but nothing happens.

I need help with this

**Comment by krikzz** [comment]
Sorry, i can't help with genesis plus gx, have no idea how to force mode1 on this emu. For tests i used real MegaCD or flashcart.
