### ISSUE TITLE
Example on how to implement MSU-MD in SGDK projects?

### ISSUE THREAD

**Issue by ghost** [krikzz/msu-md#10]
Hi, I'm making a game using Stef's SGDK library for Mega Drive development in C, and would like to use MSU-MD without the provided sys.h file.

How do I import the bin file and how do I call the MSU-MD driver?
Could you write an example of how to do that in the README file so it's easier to implement?

Thanks in advance.

**Comment by krikzz** [comment]
you just need to include driver file using asm  .incbin directive and call
the address where it include to init the driver, then you can use driver
registers. i don't think that i can explain it more clear than it already
shown in msu-md-sample at my github

ср, 28 дек. 2022 г. в 13:44, izu68 ***@***.***>:
