### ISSUE TITLE
How low is seek time with "seek time emulation" off?

### ISSUE THREAD

**Issue by ArcadeTV** [krikzz/msu-md#5]
Dear Igor,

I started using the updated driver and made audio tracks for looping seemlessly, but on MegaEDpro there is still a gap when audio is looped.
Here's an example: https://github.com/ArcadeTV/msu-md-flintstones
With the patched rom and corresponding soundPack enter Options/Sound Test and listen to No. 14 (short track, easy testing)

Thanks again for making all this possible!

**Comment by ArcadeTV** [comment]
I turn off STE like this:
```
MCD_STAT        equ $A12020             ; 0-ready, 1-init, 2-cmd busy
MCD_CMD         equ $A12010
MCD_ARG         equ $A12011
MCD_SEEK	equ $A12012
MCD_CMD_CK      equ $A1201F

    move.w  #($1600|1),MCD_CMD          ; seek time emulation switch
                                        ; 0-on(default state), 1-off(no seek delays)
    addq.b  #1,MCD_CMD_CK               ; Increment command clock
```

Any objections?

**Comment by krikzz** [comment]
> Dear Igor,
> 
> I started using the updated driver and made audio tracks for looping seemlessly, but on MegaEDpro there is still a gap when audio is looped.
> Here's an example: https://github.com/ArcadeTV/msu-md-flintstones
> With the patched rom and corresponding soundPack enter Options/Sound Test and listen to No. 14 (short track, easy testing)
> 
> Thanks again for making all this possible!

seek time should be not more than 1/75 of sec if emulation turned off

**Comment by ArcadeTV** [comment]
Thanks, then I must have made a mistake somewhere.
If I can't get it working I will have to revert all the latest soundPacks to "fade out" style.
`move.w  #($1600|1),$A12010` is correct and can be called any time?

**Comment by krikzz** [comment]
> `move.w #($1600|1),$A12010` is correct and can be called any time?

looks correct. can be called any time
